version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/app
    tty: true
    ports:
      - "8888:8888"
    entrypoint: >
      poetry run jupyter notebook
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/app
    expose:
      - "8888"